baseURL: http://example.org/
title: Hugo Themes
author: Steve Francia
paginate: 3
languageCode: en
DefaultContentLanguage: en
enableInlineShortcodes: yes
footnoteReturnLinkContents: ^
theme: harbor
Author:
  name: hugo author
permalinks:
  page: /:filename/
  post: /:year/:month/:day/:filename/
outputs:
  section:
    - JSON
    - HTML
params:
  favicon: favicon.ico
  logo:
    alt: Logo
    height: 50
    url: icon.png
    width: 50
  mainSections: post
  nav:
    - icon: fas fa-user fa-lg
      identifier: about
      name: About
      url: /about/
      weight: 3
    - icon: fas fa-tag fa-lg
      identifier: tags
      name: Tags
      url: /tags/
      weight: 3
    - icon: fas fa-search fa-lg
      identifier: search
      name: Search
      url: /search/
      weight: 3
  social:
    - icon: fab fa-twitter
      name: Twitter
      url: https://twitter.com/GoHugoIO
    - icon: fab fa-github
      name: GitHub
      url: https://github.com/gohugoio/hugo
    - icon: fab fa-reddit-alien
      name: reddit
      url: https://www.reddit.com/r/gohugo/
  social_static:
    - icon: qiita.png
      name: Qiita
      url: https://qiita.com
